# Generated by Django 6.0 on 2026-02-10 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('quests', '0002_mainquest_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_date', models.DateField()),
                ('focus_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='focused_in_sessions', to='quests.conceptnode')),
                ('reinforcement_nodes', models.ManyToManyField(blank=True, related_name='reinforced_in_sessions', to='quests.conceptnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'calendar_date', 'completed_at')},
            },
        ),
    ]
