# Generated by Django 6.0 on 2026-02-18 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_sessioncompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreakState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.PositiveIntegerField(default=0)),
                ('freeze_streak', models.PositiveIntegerField(default=0)),
                ('consecutive_zero_session_days', models.PositiveIntegerField(default=0)),
                ('last_evaluated_date', models.DateField(help_text='Last calendar date for which streak logic was evaluated')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
