# Generated by Django 6.0 on 2026-03-10 04:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userstreakstate'),
        ('quests', '0002_mainquest_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessioncompletion',
            unique_together={('user', 'focus_node')},
        ),
    ]
