# Generated by Django 6.0 on 2025-12-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainquest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
