# Generated by Django 6.0 on 2025-12-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNodePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('concept_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='quests.conceptnode')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('concept_node', 'order'), name='unique_page_order_per_concept_node')],
            },
        ),
    ]
